// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD28KKpkO7sMPh9b9ldTxOYYQ6lDo_TCIo',
    appId: '1:767272172506:web:125b556a26ff327e20dee3',
    messagingSenderId: '767272172506',
    projectId: 'book-eaf9a',
    authDomain: 'book-eaf9a.firebaseapp.com',
    storageBucket: 'book-eaf9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-9j0by4GilYjXgYwj_jV0qwt5FjOj1YA',
    appId: '1:767272172506:android:69eb37bcfbac517d20dee3',
    messagingSenderId: '767272172506',
    projectId: 'book-eaf9a',
    storageBucket: 'book-eaf9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMw4w64N2pQlbhHEfYIUWIEdoTPh6S2wo',
    appId: '1:767272172506:ios:c9f1d48bf05766ae20dee3',
    messagingSenderId: '767272172506',
    projectId: 'book-eaf9a',
    storageBucket: 'book-eaf9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMw4w64N2pQlbhHEfYIUWIEdoTPh6S2wo',
    appId: '1:767272172506:ios:c9f1d48bf05766ae20dee3',
    messagingSenderId: '767272172506',
    projectId: 'book-eaf9a',
    storageBucket: 'book-eaf9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD28KKpkO7sMPh9b9ldTxOYYQ6lDo_TCIo',
    appId: '1:767272172506:web:868cd4ba41971dd320dee3',
    messagingSenderId: '767272172506',
    projectId: 'book-eaf9a',
    authDomain: 'book-eaf9a.firebaseapp.com',
    storageBucket: 'book-eaf9a.appspot.com',
  );
}
